### ISSUE TITLE
[Bug]: crafting gold tools with 2 sticks in a deployer

### ISSUE THREAD

**Issue by J0hnnyWalkers** [Thefuzz1234555/Create-Molten-Metallurgy#2]
### Minecraft Version

1.20.1

### Mod Version

1.0.1

### Mod Loader Version

47.3.0

### Describe the bug

Hi, I just found out that you can make the golden tools that require a handle stick with just 2 sticks in a deployer.

Is it a BUG or a Feature?

### Steps to Reproduce

Just build the setup as in the pic

### Crash Reports/Logs

.

### Screenhots

![2024-08-04_21 06 55](https://github.com/user-attachments/assets/4624d5f2-92f5-4620-ba36-88c717caf7e1)

### Mod List

![grafik](https://github.com/user-attachments/assets/0cdd1ab3-e669-4b29-8ea1-79884d322a81)

**Comment by watersofnazareth** [comment]
Oh that's hilarious, I know the issue, and I'll work on a fix, deploying a stick twice shouldn't give you gold

**Comment by watersofnazareth** [comment]
Expect a small patch for this that'll add some new transitional items, should help with the recipes and how they appear when being made

**Comment by watersofnazareth** [comment]
Fixed as of 1.0.2!
