### ISSUE TITLE
[Bug]: Missing recipes

### ISSUE THREAD

**Issue by Sanche2597** [Thefuzz1234555/Create-Molten-Metallurgy#4]
### Minecraft Version

1.20.1

### Mod Version

1.0.1

### Mod Loader Version

forge 45.3.0

### Describe the bug

after installed this mod and the mod "supplymentaries", some recipes like chests are missing. In JEI, it shows "Empty tags: minecraft:planks". This issue also occurs in recipes that includes irons.
[latest.log](https://github.com/user-attachments/files/16659186/latest.log)

### Steps to Reproduce

1.install "supplymentaries" and this mod
2. launch the game and look up recipes of any wood planks
3. find lots of recipes missing

### Crash Reports/Logs

the log is on the description window

### Mod List

supplymentaries, create, create:molten metallurgy

**Comment by Sanche2597** [comment]
![image](https://github.com/user-attachments/assets/0d2d03e6-e9aa-4ec5-b568-bd99e7426682)

**Comment by Sanche2597** [comment]
I rly LOVE ur mod, so plz. :)

**Comment by watersofnazareth** [comment]
That's an odd bug, I'll have to look into it not entirely sure why this'd happen with Supplementary

**Comment by OxiiGiin1** [comment]
It doesn't happen with just Supplementaries. I have a modpack that includes Mekanism and Create (with some addons) and it seems to throw the tag error still. Weirdly enough the error is only thrown on my dedicated server and not when I make a single player world for some reason. [both pictures are with the same modpack]
![2024-08-25_21 03 01](https://github.com/user-attachments/assets/fa000a5f-b482-45e8-87c8-2668abe24200)
*first pic is single player with the iron recipes loaded properly*
![2024-08-25_21 04 45](https://github.com/user-attachments/assets/fa536bd6-66d0-4fe9-a7e9-63d515054cfc)
*second pic is on the server with all the tag errors*

**Comment by watersofnazareth** [comment]
Interesting, do you mind providing your modlist @OxiiGiin1?

**Comment by watersofnazareth** [comment]
I'm not actually seeing any compat issues with Supplementaries strangely, so far this seems like an issue that might have caused some tag loading issues whenever the ingots and nuggets were removed and replaced for better mod support, let me know if you can were you using 1.0.2 or lower prior to the update?

**Comment by watersofnazareth** [comment]
I think I may have found the issue, I'll try putting a patch out tomorrow that'll also have Twilight Forest support

**Comment by watersofnazareth** [comment]
Closing as of 1.0.4, let me know if you experience any additional issues
